# Generated by Django 4.1.2 on 2022-10-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_number', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('max_capacity', models.IntegerField()),
                ('curr_capacity', models.IntegerField()),
            ],
        ),
    ]
