# Generated by Django 4.1.3 on 2022-11-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trucks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="truck", old_name="brand", new_name="model",),
    ]
